name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: 'Build and Restart'
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        echo "${{ secrets.BE_ENV_FILE }}" > .env
        cd apps/plia
        echo "${{ secrets.FE_ENV_FILE }}" > .env
        cd ../../
        npm i
        npm run build
        pm2 restart 0
        pm2 restart 1
        pm2 save
